[package]
name = "koko-server"
version = "0.1.0"
edition = "2024"

[dependencies]
koko-core = { path = "../core" }
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "uuid", "macros", "json", "time"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
serde_json = "1"
