#[path = "入口.rs"]
pub mod entry;
#[path = "总装.rs"]
pub mod assembly;
#[path = "契约.rs"]
pub mod contract;
#[path = "用例.rs"]
pub mod usecase;
#[path = "领域/mod.rs"]
pub mod domain;
#[path = "适配.rs"]
pub mod adapter;
